name: talentstream
description: "A production-grade, feature-rich job board application built with Flutter, focusing on state-driven UIs and robust offline caching."# The following line prevents the package from being accidentally published to
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  url_launcher: ^6.1.7
  curved_navigation_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
